# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regform', '0002_auto_20160404_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertable',
            name='middle_name',
        ),
        migrations.AlterField(
            model_name='usertable',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
