# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regform', '0005_auto_20160404_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='middle_name',
            field=models.CharField(max_length=50, verbose_name='middle_name'),
        ),
    ]
