# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regform', '0008_auto_20160407_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='email',
            field=models.EmailField(max_length=15, unique=True),
        ),
    ]
