# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regform', '0009_auto_20160412_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
