# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regform', '0010_auto_20160414_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
