# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regform', '0011_auto_20160415_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='alternate_mobile_no',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='usertable',
            name='country',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='usertable',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertable',
            name='ethnicity',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='usertable',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usertable',
            name='languages_known',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
