# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regform', '0012_auto_20160418_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='alternate_mobile_no',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='country',
            field=models.CharField(choices=[('am', 'America'), ('eu', 'Europe'), ('asi', 'Asia'), ('af', 'Africa'), ('au', 'Australia'), ('oc', 'Oceania'), ('an', 'Antartica')], default='AM', max_length=10),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='date_of_birth',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='ethnicity',
            field=models.CharField(choices=[('ame', 'American'), ('eup', 'Europeon'), ('afr', 'African'), ('aus', 'Australian')], default='AM', max_length=5),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='m', max_length=50),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='languages_known',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ch', 'China')], default='EN', max_length=7),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='mobile_no',
            field=models.CharField(max_length=15),
        ),
    ]
