# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 07:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('regform', '0013_auto_20160424_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='error',
            field=models.CharField(default=datetime.datetime(2016, 4, 27, 7, 16, 5, 54000, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usertable',
            name='alternate_mobile_no',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
